Update .cspell.json
tier4/autoware-spell-check-dict pull request #148
Opened 2021-10-01 07:57 UTC by YoheiMishina

Added name of engineer

2021-10-05 03:12 UTC, kmiya requested changes

2021-10-05 03:12 UTC, kmiya commented on cspell/.cspell.json
> +        "Yushi"
```suggestion
        "Yushi",
```
The trailing comma is needed.

2021-10-05 10:21 UTC, merged

2021-10-05 10:21 UTC, kmiya commented
Thanks!

2021-10-06 00:46 UTC, YoheiMishina commented
ありがとうございました！